import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Next _Asikur",
  description: "Generated by Next _Asikur",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <header>
            <Header />
          </header>
          {children}

          {/* <footer className="fixed bottom-10  text-center">Footer</footer> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
